### ISSUE TITLE
Feature request - Allow XP bottles to go over 100xp

### ISSUE THREAD

**Issue by anoomolu** [wendeburg/deterministic-xp-bottles#2]
Hiya! Sorry for closing the other issue, thought I'd make another one just related to this feature request. XP bottles are pretty rare if not abusing villager trading, so I was wondering if it'd be possible to allow the XP produced from a bottle to go over 100xp - my use case is setting them to drop 117xp, or 1/10 of the way to level 30 when ran with Curve mode from the Linear Levels mod.

Thank you!

**Comment by wendeburg** [comment]
I released a new version for MC 1.20.4, one of the changes being the one in your request.

**Comment by anoomolu** [comment]
> Hi, sorry for the delayed response. Yeah i'll implement that feature. For which minecraft version do you need it? (1.20.1, 1.20.2) I'll also modify it for the 1.20.4 release.

Would 1.20.1 be okay? I think that's the version most people are sticking to for modpacks

**Comment by wendeburg** [comment]
Hey, I released the version 0.1.1 for MC 1.20.1 with the changes you requested :)
